spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/jpashop
    username: sa
    password:
    drvier-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hiberante:
        show-sql: true
        format-sql: true

logging:
  level:
    org.hibernate.SQL: debug
