spring:
  datasource:
    url: jdbc:h2:~/jpashop;MVCC=true
    username: sa
    password:
    drvier-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auth: create
    properties:
      hiberante:
        show-sql: true
        format-sql: true

logging:
  level:
    org.hibernate.SQL: debug
